/**:
  ros__parameters:
    # control parameters
    controller_freq_hz: 50.0 # hz

    max_angular_vel_rps: 0.05 # rad/s
    max_angle_delta_rad: 0.001 # radian
    min_angle_delta_rad: 0.001 # radian

    angle_tolerance_rad: 0.0523599 # radian (3 deg)

    weight_rate: 0.2
    # control parameters
